export enum SkillType
{
  BASIC_ATTACK = "BASIC_ATTACK",
  RESONANCE_SKILL = "RESONANCE_SKILL",
  RESONANCE_LIBERATION = "RESONANCE_LIBERATION",
  INHERENT_SKILL_01 = "INHERENT_SKILL_01",
  INHERENT_SKILL_02 = "INHERENT_SKILL_02",
  FORTE_CIRCUIT = "FORTE_CIRCUIT",
  INTRO_SKILL = "INTRO_SKILL",
  OUTRO_SKILL = "OUTRO_SKILL",
  BONUS = "BONUS",
}
