<script setup lang="ts">
import type { WuwaOptimizerExport } from '~/Core/ImportExport/WuwaOptimizerExport'
import type { WuwaOptimizerImportPreview } from '~/Core/ImportExport/WuwaOptimizerImport'
import type Echo from '~/Core/Interfaces/Echo'
import type { KameraCharactersJson, KameraEchoesJson } from '~/Core/ImportExport/KameraImport'
import { ConvertKameraToWuwaOptimizerExport } from '~/Core/ImportExport/KameraImport'
import {
  CreateWuwaOptimizerImportPlan,
  CreateWuwaOptimizerImportPreview,
} from '~/Core/ImportExport/WuwaOptimizerImport'

const KAMERA_DOWNLOAD_URL = 'https://github.com/Jjcorsino/wuwa-optimizer/releases?q=scanner'

const CharactersStore = useCharactersStore()
const WeaponsStore = useWeaponsStore()
const EchoesStore = useEchoesStore()
const BuildsStore = useBuildsStore()

const CharactersFile = ref<File | undefined>(undefined)
const EchoesFile = ref<File | undefined>(undefined)

const ParsedExport = ref<WuwaOptimizerExport | undefined>(undefined)
const Preview = ref<WuwaOptimizerImportPreview | undefined>(undefined)
const SkippedEchoes = ref(0)
const SkippedCharacters = ref(0)
const ErrorMessage = ref<string | undefined>(undefined)
const SuccessMessage = ref<string | undefined>(undefined)
const IsImporting = ref(false)
const IsParsing = ref(false)

const HasFiles = computed(() => CharactersFile.value !== undefined || EchoesFile.value !== undefined)
const BlockingIssues = computed(() => Preview.value?.issues.filter(i => i.severity === 'error') ?? [])
const ReviewIssues = computed(() => Preview.value?.issues.filter(i => i.severity !== 'error') ?? [])

function resetState() {
  ParsedExport.value = undefined
  Preview.value = undefined
  ErrorMessage.value = undefined
  SuccessMessage.value = undefined
  SkippedEchoes.value = 0
  SkippedCharacters.value = 0
}

function onFileChange() {
  resetState()
}

async function parseFiles() {
  if (!HasFiles.value) return

  IsParsing.value = true
  resetState()

  try {
    let characters: KameraCharactersJson | undefined
    let echoes: KameraEchoesJson | undefined

    if (CharactersFile.value) {
      const text = await CharactersFile.value.text()
      characters = JSON.parse(text) as KameraCharactersJson
    }

    if (EchoesFile.value) {
      const text = await EchoesFile.value.text()
      echoes = JSON.parse(text) as KameraEchoesJson
    }

    const result = ConvertKameraToWuwaOptimizerExport(characters, echoes)
    SkippedEchoes.value = result.skippedEchoes
    SkippedCharacters.value = result.skippedCharacters
    ParsedExport.value = result.export
    Preview.value = CreateWuwaOptimizerImportPreview(result.export)
  }
  catch (error) {
    ErrorMessage.value = error instanceof SyntaxError
      ? 'Invalid JSON in one of the uploaded files. Make sure you are uploading the files generated by WuWa Inventory Kamera.'
      : (error instanceof Error ? error.message : 'Failed to parse files.')
  }
  finally {
    IsParsing.value = false
  }
}

function onClear() {
  CharactersFile.value = undefined
  EchoesFile.value = undefined
  resetState()
}

function onImport() {
  if (!ParsedExport.value || !Preview.value?.canImport) return

  IsImporting.value = true
  ErrorMessage.value = undefined
  SuccessMessage.value = undefined

  try {
    const plan = CreateWuwaOptimizerImportPlan(ParsedExport.value)

    plan.characters.forEach(c => CharactersStore.UpdateById(c.Id, c))
    plan.weapons.forEach(w => WeaponsStore.AddOrUpdate(w))
    plan.echoes.forEach(e => EchoesStore.Upsert(e))
    plan.loadouts.forEach((loadout) => {
      const character = CharactersStore.GetById(loadout.characterId)
      const weapon = loadout.weaponId ? WeaponsStore.GetById(loadout.weaponId) : undefined
      const echoes = loadout.echoIds
        .map(id => EchoesStore.GetById(id))
        .filter((e): e is Echo => e !== undefined)

      BuildsStore.CreateBuild(loadout.name, character, weapon, echoes)
    })

    SuccessMessage.value = `Imported ${plan.characters.length} characters, ${plan.weapons.length} weapons, and ${plan.echoes.length} echoes.`
  }
  catch (error) {
    ErrorMessage.value = error instanceof Error ? error.message : 'Import failed.'
  }
  finally {
    IsImporting.value = false
  }
}

function getIssueColor(severity: WuwaOptimizerImportPreview['issues'][number]['severity']) {
  if (severity === 'error') return 'error'
  if (severity === 'warning') return 'warning'
  return 'neutral'
}
</script>

<template>
  <div class="mx-auto my-8 max-w-7xl text-gray-300">
    <div class="flex flex-col gap-8">

      <!-- Step 1: Download -->
      <section class="border border-neutral-800 bg-neutral-950/40 p-6">
        <div class="flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div class="flex gap-4 items-start">
            <div class="mt-1 flex size-10 shrink-0 items-center justify-center rounded-full border border-neutral-700 bg-neutral-900 text-sm font-bold text-primary-400">
              1
            </div>
            <div>
              <h3 class="font-semibold text-gray-100">
                Download WuWa Inventory Kamera
              </h3>
              <p class="mt-1 text-sm text-gray-400">
                An open-source scanner that reads your Wuthering Waves profile directly from the game window using OCR.
                Run it while the game is open in fullscreen at 1680×1050, 1920×1080, or 2560×1440.
              </p>
              <p class="mt-2 text-xs text-gray-500">
                Scan your characters, echoes, and weapons — then come back here with the generated JSON files.
              </p>
            </div>
          </div>
          <a
            :href="KAMERA_DOWNLOAD_URL"
            target="_blank"
            rel="noopener noreferrer"
          >
            <UButton
              icon="i-carbon-download"
              color="primary"
              size="lg"
              class="whitespace-nowrap"
            >
              Download Scanner
            </UButton>
          </a>
        </div>
      </section>

      <!-- Step 2: Upload -->
      <section class="border border-neutral-800 bg-neutral-950/40 p-6">
        <div class="flex gap-4 items-start mb-6">
          <div class="mt-1 flex size-10 shrink-0 items-center justify-center rounded-full border border-neutral-700 bg-neutral-900 text-sm font-bold text-primary-400">
            2
          </div>
          <div>
            <h3 class="font-semibold text-gray-100">
              Upload your scanned files
            </h3>
            <p class="mt-1 text-sm text-gray-400">
              After scanning, WuWa Inventory Kamera generates JSON files in its output folder.
              Upload <span class="font-mono text-gray-300">characters.json</span> and/or <span class="font-mono text-gray-300">echoes.json</span> below.
            </p>
          </div>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <p class="mb-2 text-xs font-medium uppercase tracking-wide text-gray-500">
              characters.json
              <span class="ml-1 text-gray-600">(recommended)</span>
            </p>
            <UFileUpload
              v-model="CharactersFile"
              size="lg"
              accept="application/json,.json"
              variant="area"
              class="min-h-32"
              label="Drop characters.json"
              description="Level, skills, sequences & equipped weapon"
              @change="onFileChange"
            />
          </div>

          <div>
            <p class="mb-2 text-xs font-medium uppercase tracking-wide text-gray-500">
              echoes.json
              <span class="ml-1 text-gray-600">(optional)</span>
            </p>
            <UFileUpload
              v-model="EchoesFile"
              size="lg"
              accept="application/json,.json"
              variant="area"
              class="min-h-32"
              label="Drop echoes.json"
              description="Full echo inventory with stats"
              @change="onFileChange"
            />
          </div>
        </div>

        <div class="mt-4 flex flex-wrap gap-3">
          <UButton
            icon="i-carbon-view"
            color="neutral"
            :disabled="!HasFiles"
            :loading="IsParsing"
            @click="parseFiles"
          >
            Preview
          </UButton>
          <UButton
            icon="i-carbon-trash-can"
            color="neutral"
            variant="ghost"
            :disabled="!HasFiles && !Preview"
            @click="onClear"
          >
            Clear
          </UButton>
        </div>
      </section>

      <!-- Step 3: Preview & Import -->
      <section class="border border-neutral-800 bg-neutral-950/40 p-6">
        <div class="flex gap-4 items-start mb-6">
          <div class="mt-1 flex size-10 shrink-0 items-center justify-center rounded-full border border-neutral-700 bg-neutral-900 text-sm font-bold text-primary-400">
            3
          </div>
          <div>
            <h3 class="font-semibold text-gray-100">
              Review and import
            </h3>
            <p class="mt-1 text-sm text-gray-400">
              Verify the preview below and confirm the import.
            </p>
          </div>
        </div>

        <!-- Error -->
        <div v-if="ErrorMessage" class="mb-4">
          <UAlert
            color="error"
            variant="subtle"
            title="Parse error"
            :description="ErrorMessage"
          />
        </div>

        <!-- Preview loaded -->
        <div v-else-if="Preview" class="flex flex-col gap-5">

          <!-- Header -->
          <div class="flex flex-wrap items-center justify-between gap-3">
            <div>
              <h4 class="text-base font-medium text-gray-100">
                Import Preview
              </h4>
              <p class="text-sm text-gray-400">
                Source: WuWa Inventory Kamera
              </p>
            </div>
            <UBadge :color="Preview.canImport ? 'success' : 'error'" variant="subtle">
              {{ Preview.canImport ? 'Ready to import' : 'Blocked' }}
            </UBadge>
          </div>

          <!-- Counts -->
          <div class="grid grid-cols-2 md:grid-cols-4 gap-3">
            <div class="border border-neutral-800 bg-neutral-950 p-3">
              <div class="text-2xl font-semibold text-gray-100">
                {{ Preview.counts.characters }}
              </div>
              <div class="text-xs uppercase tracking-wide text-gray-500">
                Characters
              </div>
            </div>
            <div class="border border-neutral-800 bg-neutral-950 p-3">
              <div class="text-2xl font-semibold text-gray-100">
                {{ Preview.counts.weapons }}
              </div>
              <div class="text-xs uppercase tracking-wide text-gray-500">
                Weapons
              </div>
            </div>
            <div class="border border-neutral-800 bg-neutral-950 p-3">
              <div class="text-2xl font-semibold text-gray-100">
                {{ Preview.counts.echoes }}
              </div>
              <div class="text-xs uppercase tracking-wide text-gray-500">
                Echoes
              </div>
            </div>
            <div class="border border-neutral-800 bg-neutral-950 p-3">
              <div class="text-2xl font-semibold text-gray-100">
                {{ Preview.counts.equipped }}
              </div>
              <div class="text-xs uppercase tracking-wide text-gray-500">
                Loadouts
              </div>
            </div>
          </div>

          <!-- Skipped items notice -->
          <UAlert
            v-if="SkippedEchoes > 0 || SkippedCharacters > 0"
            color="warning"
            variant="subtle"
            title="Some items were skipped"
            :description="`${SkippedEchoes > 0 ? `${SkippedEchoes} echo(es)` : ''}${SkippedEchoes > 0 && SkippedCharacters > 0 ? ' and ' : ''}${SkippedCharacters > 0 ? `${SkippedCharacters} character(s)` : ''} could not be matched to game data and were excluded.`"
          />

          <!-- Issues -->
          <div v-if="BlockingIssues.length || ReviewIssues.length" class="flex flex-col gap-2">
            <div
              v-for="issue in Preview.issues"
              :key="`${issue.code}-${issue.path}-${issue.message}`"
              class="border border-neutral-800 bg-neutral-950 p-3"
            >
              <div class="flex flex-wrap items-center gap-2">
                <UBadge :color="getIssueColor(issue.severity)" variant="subtle">
                  {{ issue.severity }}
                </UBadge>
                <span class="font-mono text-xs text-gray-500">{{ issue.code }}</span>
                <span v-if="issue.path" class="font-mono text-xs text-gray-600">{{ issue.path }}</span>
              </div>
              <p class="mt-2 text-sm text-gray-300">
                {{ issue.message }}
              </p>
            </div>
          </div>

          <!-- Success -->
          <UAlert
            v-if="SuccessMessage"
            color="success"
            variant="subtle"
            title="Import complete"
            :description="SuccessMessage"
          />

          <div class="flex justify-end">
            <UButton
              color="primary"
              size="lg"
              icon="i-carbon-save"
              :loading="IsImporting"
              :disabled="!Preview.canImport || !!SuccessMessage"
              @click="onImport"
            >
              Import Data
            </UButton>
          </div>
        </div>

        <!-- Empty state -->
        <div v-else class="flex h-40 items-center justify-center text-sm text-gray-600">
          Upload your files and click Preview to continue.
        </div>
      </section>

    </div>
  </div>
</template>
